// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2017  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================
/**
 * This class was generated using exec.php
 * against an XML schema provided by Kaltura.
 * 
 * MANUAL CHANGES TO THIS CLASS WILL BE OVERWRITTEN.
 */
public enum LanguageCode: String {
	case AA = "aa"
	case AB = "ab"
	case AF = "af"
	case AM = "am"
	case AR = "ar"
	case AS_ = "as"
	case AY = "ay"
	case AZ = "az"
	case BA = "ba"
	case BE = "be"
	case BG = "bg"
	case BH = "bh"
	case BI = "bi"
	case BN = "bn"
	case BO = "bo"
	case BR = "br"
	case CA = "ca"
	case CO = "co"
	case CS = "cs"
	case CY = "cy"
	case DA = "da"
	case DE = "de"
	case DZ = "dz"
	case EL = "el"
	case EN = "en"
	case EN_GB = "en_gb"
	case EN_US = "en_us"
	case EO = "eo"
	case ES = "es"
	case ET = "et"
	case EU = "eu"
	case FA = "fa"
	case FI = "fi"
	case FJ = "fj"
	case FO = "fo"
	case FR = "fr"
	case FY = "fy"
	case GA = "ga"
	case GD = "gd"
	case GL = "gl"
	case GN = "gn"
	case GU = "gu"
	case GV = "gv"
	case HA = "ha"
	case HE = "he"
	case HI = "hi"
	case HR = "hr"
	case HU = "hu"
	case HY = "hy"
	case IA = "ia"
	case ID = "id"
	case IE = "ie"
	case IK = "ik"
	case IN = "in"
	case IS = "is"
	case IT = "it"
	case IU = "iu"
	case IW = "iw"
	case JA = "ja"
	case JI = "ji"
	case JV = "jv"
	case KA = "ka"
	case KK = "kk"
	case KL = "kl"
	case KM = "km"
	case KN = "kn"
	case KO = "ko"
	case KS = "ks"
	case KU = "ku"
	case KY = "ky"
	case LA = "la"
	case LI = "li"
	case LN = "ln"
	case LO = "lo"
	case LT = "lt"
	case LV = "lv"
	case MG = "mg"
	case MI = "mi"
	case MK = "mk"
	case ML = "ml"
	case MN = "mn"
	case MO = "mo"
	case MR = "mr"
	case MS = "ms"
	case MT = "mt"
	case MU = "multilingual"
	case MY = "my"
	case NA = "na"
	case NE = "ne"
	case NL = "nl"
	case NO = "no"
	case OC = "oc"
	case OM = "om"
	case OR_ = "or"
	case PA = "pa"
	case PL = "pl"
	case PS = "ps"
	case PT = "pt"
	case QU = "qu"
	case RM = "rm"
	case RN = "rn"
	case RO = "ro"
	case RU = "ru"
	case RW = "rw"
	case SA = "sa"
	case SD = "sd"
	case SG = "sg"
	case SH = "sh"
	case SI = "si"
	case SK = "sk"
	case SL = "sl"
	case SM = "sm"
	case SN = "sn"
	case SO = "so"
	case SQ = "sq"
	case SR = "sr"
	case SS = "ss"
	case ST = "st"
	case SU = "su"
	case SV = "sv"
	case SW = "sw"
	case TA = "ta"
	case TE = "te"
	case TG = "tg"
	case TH = "th"
	case TI = "ti"
	case TK = "tk"
	case TL = "tl"
	case TN = "tn"
	case TO = "to"
	case TR = "tr"
	case TS = "ts"
	case TT = "tt"
	case TW = "tw"
	case UG = "ug"
	case UK = "uk"
	case UR = "ur"
	case UZ = "uz"
	case VI = "vi"
	case VO = "vo"
	case WO = "wo"
	case XH = "xh"
	case YI = "yi"
	case YO = "yo"
	case ZH = "zh"
	case ZU = "zu"
}
