name: "CI"

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest
    environment: Kaltura_2222401

    steps:
    - uses: actions/checkout@v3
    - name: Updating CocoaPods repo
      run: pod repo update
    - name: Setup Environment
      run: |
        sed -e "s#@YOUR_PARTNER_ID@#${{ secrets.PARTNER_ID }}#g" -e "s#@YOUR_ADMIN_SECRET@#${{ secrets.SECRET }}#g" -e "s#@SERVER_URL@#${{ secrets.SERVER_URL }}#g" Example/Tests/TestsConfig.template.plist > Example/Tests/TestsConfig.plist
    - name: Install CocoaPods
      working-directory: ./Example
      run: pod install
    - name: Build
      working-directory: ./Example
      run: xcodebuild -workspace "KalturaClient.xcworkspace" -scheme "KalturaClient-Example" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.2' clean test | xcpretty
#xcodebuild clean build test -workspace Example/KalturaClient.xcworkspace -scheme KalturaClient_Tests -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' > $BUILD_OUTPUT 2>&1
