name: CocoaPods push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pods_push:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Updating CocoaPods repo
      run: pod repo update
    - name: CocoaPods push
      run: |
       PODS_USER=${{ secrets.PODS_USER }} PODS_PASS=${{ secrets.PODS_PASS }} sh .github/cocoapods_publish.sh
#     - uses: ncipollo/release-action@v1
#       with:
#         bodyFile: ".github/release_notes.md"
#         token: ${{ secrets.GITHUB_TOKEN }}
#         draft: false
        
